- name: Get Credentials
  hosts: all
  gather_facts: false
  connection: local
  vars_prompt:
    - name: linode_token
      prompt: What is your Linode token?
      private: yes

  tasks:
  - name: Save credentials as global vars
    set_fact:
      linode_token: "{{ linode_token }}"
    no_log: true

- name: Destroy Terraform
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    deploy: false
  roles:
    - { role: terraform }
