- name: Deploy Terraform
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    state: "{{ state }}"
    force_init: true
    variables:
      linode_token: "{{ linode_token }}"
