- name: Destroy Terraform
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    state: "{{ state }}"
    force_init: false
    variables:
      ansible_ssh_key_private: "{{ lookup('file', '{{ ansible_ssh_private_key_file }}') }}"
      linode_token: "{{ linode_token }}"
